#include<stdio.h>
#include<conio.h>
int add(int a,int b)
{
	return a+b;
}
int sub(int a,int b)
{
	return a-b;
}
int mul(int a,int b)
{
	return a*b;
}
int div(int a,int b)
{
      if(b==0)
       {
void main()
{
	int a,b;
	clrscr();
	printf("\nenter value : ");
	scanf("%d",&a);
	printf("\nenter value : ");
	scanf("%d",&b);
	printf("\naddition : %d",add(a,b));
	printf("\nsubstration : %d",sub(a,b));
	printf("\ndivision : %d",div(a,b));
	printf("\nmodution : %d",mod(a,b));
	printf("\nmultiplication : %d",mul(a,b));
	getch();
}


































